import { describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildFindings,
  inspectGatewayCache,
  inspectPlannedLaunchers,
  redactForClaudeDoctor,
  sanitizeClaudeDoctorReport,
  resolveRawClaudeOnPath,
  summarizeApiModels,
  inspectClaudeGrants,
  type FileSystemProbe,
  type ClaudeDoctorReport,
  type ClaudeGrantsInspection,
} from "../src/claude-doctor";
import { addClaudeGrant } from "../src/claude-grants";
import type { FrogConfig } from "../src/types";

/** Portable Claude executable fixture name: bare `claude` on POSIX, PATHEXT-suffixed on Windows. */
const CLAUDE_EXE = process.platform === "win32" ? "claude.exe" : "claude";
const MANAGED_LAUNCHER_SUFFIX = process.platform === "win32" ? ".cmd" : "";

function fakeFs(files: Record<string, string>, realpaths: Record<string, string> = {}): FileSystemProbe {
  return {
    existsSync: (path: string) => Object.prototype.hasOwnProperty.call(files, path),
    readFileSync: (path: string) => {
      if (!Object.prototype.hasOwnProperty.call(files, path)) throw new Error(`missing ${path}`);
      return files[path]!;
    },
    realpathSync: (path: string) => realpaths[path] ?? path,
  };
}

const config: FrogConfig = {
  port: 10100,
  defaultProvider: "codex",
  providers: {
    codex: { adapter: "openai-chat", baseUrl: "https://codex.example/v1", models: ["gpt-5.5"] },
  },
  claudeProfiles: {
    schemaVersion: 1,
    defaultProfileId: "work",
    profiles: [
      { id: "work", name: "Work", claudeHome: "/tmp/.claude-work" },
      { id: "personal", name: "Personal", claudeHome: "/tmp/.claude-personal" },
    ],
  },
};

const repoRoot = dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
const cliPath = join(repoRoot, "src", "cli.ts");
const ANSI_PATTERN = /\x1b\[[0-9;]*m/;

function writeExecutable(path: string, content: string): void {
  writeFileSync(path, content, "utf8");
  chmodSync(path, 0o755);
}

function runCli(argv: string[], frogHome: string, extraEnv: Record<string, string> = {}) {
  const claudeHome = join(frogHome, "claude-home");
  mkdirSync(claudeHome, { recursive: true });
  return spawnSync(process.execPath, [cliPath, ...argv], {
    cwd: repoRoot,
    env: { ...process.env, FROGPROGSY_HOME: frogHome, CLAUDE_HOME: claudeHome, ...extraEnv },
    encoding: "utf8",
    timeout: 15_000,
  });
}

describe("Claude doctor pure helpers", () => {
  test("classifies cmux raw claude before managed launcher without using real target resolution", () => {
    const cmuxDir = "/tmp/cmux-cli-shims";
    const managedDir = "/tmp/frog/bin";
    const cmuxClaude = join(cmuxDir, CLAUDE_EXE);
    const managedClaude = join(managedDir, CLAUDE_EXE);
    const fs = fakeFs({
      [cmuxClaude]: "#!/bin/sh\nexec cmux claude\n",
      [managedClaude]: "#!/bin/sh\n# Generated by frogprogsy\n",
    });

    expect(resolveRawClaudeOnPath({ pathEnv: [cmuxDir, managedDir].join(delimiter), launcherBinDir: managedDir, fs })).toMatchObject({
      kind: "cmux_shim",
      path: cmuxClaude,
      realPath: cmuxClaude,
    });
  });

  test("managed launcher wins when it is first on PATH", () => {
    const managedDir = "/tmp/frog/bin";
    const cmuxDir = "/tmp/cmux-cli-shims";
    const managedClaude = join(managedDir, CLAUDE_EXE);
    const cmuxClaude = join(cmuxDir, CLAUDE_EXE);
    const fs = fakeFs({
      [managedClaude]: "#!/bin/sh\n# Generated by frogprogsy\n",
      [cmuxClaude]: "#!/bin/sh\nexec cmux claude\n",
    });

    expect(resolveRawClaudeOnPath({ pathEnv: [managedDir, cmuxDir].join(delimiter), launcherBinDir: managedDir, fs }).kind).toBe("managed_launcher");
  });

  test("reports missing claude-work and claude-personal launchers on PATH/installed summary", () => {
    const binDir = "/tmp/frog/bin";
    const fs = fakeFs({
      [join(binDir, `claude${MANAGED_LAUNCHER_SUFFIX}`)]: "#!/bin/sh\n# Generated by frogprogsy\n",
      [join(binDir, `claude-work${MANAGED_LAUNCHER_SUFFIX}`)]: "#!/bin/sh\n# Generated by frogprogsy\n",
    });

    const launchers = inspectPlannedLaunchers(config, { pathEnv: "/usr/bin", launcherBinDir: binDir, fs });
    expect(launchers.find(launcher => launcher.command === "claude-work")).toMatchObject({ installed: true, onPath: false });
    expect(launchers.find(launcher => launcher.command === "claude-personal")).toMatchObject({ installed: false, onPath: false });
  });

  test("inspects gateway cache healthy, missing, and malformed states", () => {
    const healthyHome = "/tmp/healthy-claude";
    const malformedHome = "/tmp/malformed-claude";
    const healthyPath = join(healthyHome, "cache", "gateway-models.json");
    const malformedPath = join(malformedHome, "cache", "gateway-models.json");
    const fetchedAt = 1_700_000_000_000;
    const now = fetchedAt + 5_000;
    const fs = fakeFs({
      [healthyPath]: JSON.stringify({ baseUrl: "http://localhost:10100", fetchedAt, models: [{ id: "claude-frogp-codex-gpt-5-5", display_name: "codex/gpt-5.5" }] }),
      [malformedPath]: "{ nope",
    });

    expect(inspectGatewayCache(healthyHome, ["claude-frogp-codex-gpt-5-5"], fs, now)).toMatchObject({
      status: "healthy",
      baseUrl: "http://localhost:10100",
      fetchedAt,
      ageMs: 5_000,
      modelCount: 1,
      ids: ["claude-frogp-codex-gpt-5-5"],
      displayNames: ["codex/gpt-5.5"],
      expectedAliasesPresent: ["claude-frogp-codex-gpt-5-5"],
      expectedAliasesMissing: [],
    });
    expect(inspectGatewayCache("/tmp/missing-claude", ["claude-frogp-codex-gpt-5-5"], fs)).toMatchObject({
      status: "missing",
      modelCount: 0,
      expectedAliasesMissing: ["claude-frogp-codex-gpt-5-5"],
    });
    expect(inspectGatewayCache(malformedHome, ["claude-frogp-codex-gpt-5-5"], fs)).toMatchObject({
      status: "malformed",
      modelCount: 0,
    });
  });

  test("treats a legacy/partial gateway cache as malformed and reports fetchedAt age (>= 0) for the exact P1 schema", () => {
    const home = "/tmp/aged-claude";
    const legacyHome = "/tmp/legacy-claude";
    const futureHome = "/tmp/future-claude";
    const path = join(home, "cache", "gateway-models.json");
    const legacyPath = join(legacyHome, "cache", "gateway-models.json");
    const futurePath = join(futureHome, "cache", "gateway-models.json");
    const fetchedAt = 1_700_000_000_000;
    const fs = fakeFs({
      [path]: JSON.stringify({ baseUrl: "http://localhost:10100", fetchedAt, models: [{ id: "claude-frogp-codex-gpt-5-5" }] }),
      // Legacy shape: pre-P1 caches had no baseUrl/fetchedAt, so they must read as malformed, never healthy.
      [legacyPath]: JSON.stringify({ models: [{ id: "claude-frogp-codex-gpt-5-5" }] }),
      [futurePath]: JSON.stringify({ baseUrl: "http://localhost:10100", fetchedAt: fetchedAt + 10_000, models: [] }),
    });

    const aged = inspectGatewayCache(home, [], fs, fetchedAt + 42_000);
    expect(aged.status).toBe("healthy");
    expect(aged.baseUrl).toBe("http://localhost:10100");
    expect(aged.fetchedAt).toBe(fetchedAt);
    expect(aged.ageMs).toBe(42_000);

    expect(inspectGatewayCache(legacyHome, [], fs, fetchedAt).status).toBe("malformed");

    // Clock skew: a fetchedAt in the future clamps ageMs to 0, never negative.
    expect(inspectGatewayCache(futureHome, [], fs, fetchedAt).ageMs).toBe(0);
  });

  test("rejects malformed or non-exact model entries in an otherwise current-schema gateway cache", () => {
    const emptyIdHome = "/tmp/empty-id-claude";
    const badDisplayHome = "/tmp/bad-display-claude";
    const extraEntryHome = "/tmp/extra-entry-claude";
    const extraRootHome = "/tmp/extra-root-claude";
    const fetchedAt = 1_700_000_000_000;
    const fs = fakeFs({
      [join(emptyIdHome, "cache", "gateway-models.json")]: JSON.stringify({
        baseUrl: "http://localhost:10100",
        fetchedAt,
        models: [{ id: "" }],
      }),
      [join(badDisplayHome, "cache", "gateway-models.json")]: JSON.stringify({
        baseUrl: "http://localhost:10100",
        fetchedAt,
        models: [{ id: "claude-frogp-codex-gpt-5-5", display_name: 55 }],
      }),
      [join(extraEntryHome, "cache", "gateway-models.json")]: JSON.stringify({
        baseUrl: "http://localhost:10100",
        fetchedAt,
        models: [{ id: "claude-frogp-codex-gpt-5-5", type: "model" }],
      }),
      [join(extraRootHome, "cache", "gateway-models.json")]: JSON.stringify({
        baseUrl: "http://localhost:10100",
        fetchedAt,
        models: [],
        legacy: true,
      }),
    });

    expect(inspectGatewayCache(emptyIdHome, [], fs, fetchedAt).status).toBe("malformed");
    expect(inspectGatewayCache(badDisplayHome, [], fs, fetchedAt).status).toBe("malformed");
    expect(inspectGatewayCache(extraEntryHome, [], fs, fetchedAt).status).toBe("malformed");
    expect(inspectGatewayCache(extraRootHome, [], fs, fetchedAt).status).toBe("malformed");
  });

  test("summarizes codex enabled/disabled models and expected enabled aliases", () => {
    const summary = summarizeApiModels([
      { provider: "codex", id: "codex/gpt-5.5" },
      { provider: "codex", id: "codex/gpt-5.4", disabled: true },
      { provider: "anthropic", id: "anthropic/claude-sonnet-4-6" },
    ]);

    expect(summary.codex).toEqual({
      enabledCount: 1,
      disabledCount: 1,
      enabledModelIds: ["gpt-5.5"],
      disabledModelIds: ["gpt-5.4"],
    });
    expect(summary.expectedEnabledAliases).toContainEqual({ routeKey: "codex/gpt-5.5", alias: "claude-frogp-codex-gpt-5-5" });
    expect(summary.expectedEnabledAliases).not.toContainEqual({ routeKey: "codex/gpt-5.4", alias: "claude-frogp-codex-gpt-5-4" });
  });

  test("does not expect cached aliases for forward providers", () => {
    const summary = summarizeApiModels([
      { provider: "codex", id: "codex/gpt-5.5" },
      { provider: "anthropic", id: "anthropic/claude-sonnet-4-6" },
    ], {
      ...config,
      providers: {
        codex: { adapter: "openai-responses", baseUrl: "https://codex.example/v1", authMode: "oauth", models: ["gpt-5.5"] },
        anthropic: { adapter: "anthropic", baseUrl: "https://api.anthropic.com", authMode: "forward", models: ["claude-sonnet-4-6"] },
      },
    });

    expect(summary.expectedEnabledAliases).toEqual([
      { routeKey: "codex/gpt-5.5", alias: "claude-frogp-codex-gpt-5-5" },
    ]);
  });

  test("keeps authReady:false models in management, excludes picker aliases, and gives mode-specific repair guidance", () => {
    const summary = summarizeApiModels([
      { provider: "codex", id: "codex/gpt-5.5", authReady: true },
      { provider: "codex", id: "codex/gpt-5.6", authReady: false },
      { provider: "openai", id: "openai/o5", authReady: false },
      { provider: "claude-sub", id: "claude-sub/claude-sonnet-4-6", authReady: false },
    ], {
      ...config,
      providers: {
        codex: { adapter: "openai-responses", baseUrl: "https://codex.example/v1", authMode: "oauth" },
        openai: { adapter: "openai-responses", baseUrl: "https://api.openai.com/v1", authMode: "key" },
        "claude-sub": { adapter: "anthropic", baseUrl: "https://api.anthropic.com", authMode: "claude-grant", claudeGrantId: "cg_deadbeef" },
      },
    });

    const codexProvider = summary.providers.find(provider => provider.provider === "codex");
    expect(codexProvider?.enabledModelIds).toContain("gpt-5.6");
    expect(codexProvider?.authNotReadyCount).toBe(1);
    expect(codexProvider?.authNotReadyModelIds).toEqual(["gpt-5.6"]);
    expect(codexProvider?.authMode).toBe("oauth");
    const openaiProvider = summary.providers.find(provider => provider.provider === "openai");
    expect(openaiProvider?.authNotReadyModelIds).toEqual(["o5"]);

    expect(summary.expectedEnabledAliases).toContainEqual({ routeKey: "codex/gpt-5.5", alias: "claude-frogp-codex-gpt-5-5" });
    expect(summary.expectedEnabledAliases.map(alias => alias.routeKey)).not.toContain("codex/gpt-5.6");
    expect(summary.expectedEnabledAliases.map(alias => alias.routeKey)).not.toContain("openai/o5");
    expect(summary.expectedEnabledAliases.map(alias => alias.routeKey)).not.toContain("claude-sub/claude-sonnet-4-6");

    const report: ClaudeDoctorReport = {
      rawClaude: { command: "claude", kind: "native", path: "/usr/bin/claude", realPath: "/usr/bin/claude", pathEntry: "/usr/bin", reason: "native" },
      realClaude: { command: "claude", path: "/usr/bin/claude" },
      launcherBinDir: "/tmp/frog/bin",
      launchers: [],
      profiles: [],
      gatewayCaches: [],
      modelSummary: summary,
      grants: { realClaudeKind: "native", grants: [], danglingProviderBindings: [], nativeAuthEnvConflicts: [], scopeAssumptions: [] },
      processInspection: { status: "unavailable", reason: "n/a" },
      findings: [],
    };
    const findings = buildFindings(report).filter(finding => finding.code === "provider_auth_not_ready");
    expect(findings.find(finding => finding.message.includes("codex"))?.action).toContain("frogp login codex");
    expect(findings.find(finding => finding.message.includes("openai"))?.action).toContain("API key");
    expect(findings.find(finding => finding.message.includes("claude-sub"))?.action).toContain("grant");
  });

  test("redaction shape never exposes Authorization, x-api-key, apiKey, token, secret, or custom header raw values", () => {
    const redacted = redactForClaudeDoctor({
      headers: {
        Authorization: "Bearer secret-token",
        "x-api-key": "raw-key",
        apiKey: "camel-key",
        API_KEY: "env-key",
        Cookie: "raw-cookie",
      },
      env: {
        ANTHROPIC_CUSTOM_HEADERS: "x-api-key: raw-custom\nAuthorization: raw-auth",
        sessionToken: { nested: "raw-token-object" },
      },
      nested: {
        client_secret: 12345,
      },
    });
    const snapshot = JSON.stringify(redacted);

    expect(snapshot).toContain("set_redacted");
    for (const secret of ["secret-token", "raw-key", "camel-key", "env-key", "raw-cookie", "raw-custom", "raw-auth", "raw-token-object", "12345"]) {
      expect(snapshot).not.toContain(secret);
    }
  });

  test("sanitizes report-shaped data before JSON emission", () => {
    const reportLike = {
      rawClaude: { kind: "cmux_shim", path: "/tmp/cmux-cli-shims/claude" },
      leakedProvider: { apiKey: "raw-report-api-key", API_KEY: "raw-report-env-key" },
      leakedHeaders: { Cookie: "raw-report-cookie", Authorization: "raw-report-auth", custom_headers: "raw-report-custom" },
    };
    const snapshot = JSON.stringify(sanitizeClaudeDoctorReport(reportLike as never));

    expect(snapshot).toContain("set_redacted");
    for (const secret of ["raw-report-api-key", "raw-report-env-key", "raw-report-cookie", "raw-report-auth", "raw-report-custom"]) {
      expect(snapshot).not.toContain(secret);
    }
  });
});

  test("token-free profiles never emit the sentinel warning; only sentinel carrier does", () => {
    const baseReport = {
      rawClaude: { command: "claude", kind: "cmux_shim", path: "/tmp/cmux/claude", realPath: "/tmp/cmux/claude", pathEntry: "/tmp/cmux", reason: "cmux" },
      realClaude: { command: "claude", path: "/tmp/native/claude" },
      launcherBinDir: "/tmp/frog/bin",
      launchers: [],
      profiles: [{
        profileId: "work",
        profileName: "Work",
        claudeHome: "/tmp/.claude-work",
        state: {
          settingsPath: "/tmp/.claude-work/settings.json",
          settingsFound: true,
          applied: true,
          expectedBaseUrl: "http://localhost:10100",
          actualBaseUrl: "http://localhost:10100",
          baseUrlMatchesExpected: true,
          gatewayDiscovery: true,
          profileHeaderMatches: true,
          authToken: "not_set",
          carrier: "token-free",
          modelDiscoveryReady: true,
        },
        runCommand: ["frogp", "claude", "run", "work"],
        reloadCommand: ["frogp", "claude", "reload-models", "work"],
      }],
      gatewayCaches: [],
      modelSummary: {
        providers: [],
        codex: { enabledCount: 0, disabledCount: 0, enabledModelIds: [], disabledModelIds: [] },
        expectedEnabledAliases: [],
      },
      grants: {
        realClaudeKind: "native",
        grants: [],
        danglingProviderBindings: [],
        nativeAuthEnvConflicts: [],
        scopeAssumptions: [],
      },
      processInspection: { status: "unavailable", reason: "not implemented" },
      findings: [],
    } satisfies ClaudeDoctorReport;

    // Token-free carrier reaches modelDiscoveryReady via the native OAuth passthrough, so it must never
    // trip the sentinel connectors/global-token warning.
    expect(buildFindings(baseReport).map(finding => finding.code)).not.toContain("sentinel_carrier_connectors_tradeoff");

    const sentinelReport: ClaudeDoctorReport = {
      ...baseReport,
      rawClaude: { ...baseReport.rawClaude, kind: "managed_launcher" },
      profiles: [{
        ...baseReport.profiles[0]!,
        state: { ...baseReport.profiles[0]!.state, authToken: "set_redacted", carrier: "sentinel", modelDiscoveryReady: true },
      }],
    };
    // Only a sentinel-carrier profile surfaces the connectors-disabled tradeoff warning.
    expect(buildFindings(sentinelReport).map(finding => finding.code)).toContain("sentinel_carrier_connectors_tradeoff");
  });

describe("frogp doctor claude CLI", () => {
  test("--json prints one ANSI-free redacted JSON document", () => {
    const home = mkdtempSync(join(tmpdir(), "frogp-doctor-"));
    const cmuxBin = join(home, "cmux-cli-shims");
    const managedBin = join(home, "managed");
    mkdirSync(cmuxBin, { recursive: true });
    mkdirSync(managedBin, { recursive: true });
    writeExecutable(join(cmuxBin, CLAUDE_EXE), "#!/bin/sh\nexec cmux claude\n");
    writeExecutable(join(managedBin, CLAUDE_EXE), "#!/bin/sh\n# Generated by frogprogsy\n");
    try {
      const result = runCli(["doctor", "claude", "--json"], home, {
        PATH: [cmuxBin, managedBin, process.env.PATH ?? ""].join(delimiter),
        ANTHROPIC_AUTH_TOKEN: "secret-token",
        ANTHROPIC_CUSTOM_HEADERS: "Authorization: raw-auth",
      });
      expect(result.status).toBe(0);
      expect(result.stderr).toBe("");
      expect(result.stdout).not.toMatch(ANSI_PATTERN);
      const parsed = JSON.parse(result.stdout) as { rawClaude: { kind: string }; processInspection: { status: string } };
      expect(parsed.rawClaude.kind).toBe("cmux_shim");
      expect(parsed.processInspection.status).toBe("unavailable");
      expect(result.stdout).not.toContain("secret-token");
      expect(result.stdout).not.toContain("raw-auth");
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  }, 15000);

  test("human output reports cmux and no-hot-reload guidance", () => {
    const home = mkdtempSync(join(tmpdir(), "frogp-doctor-"));
    const cmuxBin = join(home, "cmux-cli-shims");
    mkdirSync(cmuxBin, { recursive: true });
    writeExecutable(join(cmuxBin, CLAUDE_EXE), "#!/bin/sh\nexec cmux claude\n");
    try {
      const result = runCli(["doctor", "claude"], home, {
        PATH: [cmuxBin, process.env.PATH ?? ""].join(delimiter),
      });
      expect(result.status).toBe(0);
      expect(result.stderr).toBe("");
      expect(result.stdout).toContain("raw claude: cmux_shim");
      expect(result.stdout).toContain("hot-reload");
      expect(result.stdout).toContain("현재 PATH의 claude는 cmux shim입니다.");
      expect(result.stdout).toContain("frogp claude project enroll");
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  }, 15000);
});

function withGrantHome<T>(fn: (ctx: { home: string; config: FrogConfig }) => T): T {
  const prev = process.env.FROGPROGSY_HOME;
  const home = mkdtempSync(join(tmpdir(), "frogp-doctor-grants-"));
  process.env.FROGPROGSY_HOME = home;
  try {
    const config: FrogConfig = { port: 10100, defaultProvider: "codex", providers: {} };
    return fn({ home, config });
  } finally {
    if (prev === undefined) delete process.env.FROGPROGSY_HOME;
    else process.env.FROGPROGSY_HOME = prev;
    rmSync(home, { recursive: true, force: true });
  }
}

function reportWithGrants(grants: ClaudeGrantsInspection): ClaudeDoctorReport {
  return {
    rawClaude: { command: "claude", kind: "native", path: "/usr/bin/claude", realPath: "/usr/bin/claude", pathEntry: "/usr/bin", reason: "native" },
    realClaude: { command: "claude", path: "/usr/bin/claude" },
    launcherBinDir: "/tmp/frog-bin",
    launchers: [],
    profiles: [],
    gatewayCaches: [],
    modelSummary: { providers: [], codex: { enabledCount: 0, disabledCount: 0, enabledModelIds: [], disabledModelIds: [] }, expectedEnabledAliases: [] },
    grants,
    processInspection: { status: "unavailable", reason: "n/a" },
    findings: [],
  };
}

describe("Claude doctor grant inspection", () => {
  test("reports a confined, marker-bound grant with an injected scoped credential state", () => {
    withGrantHome(({ config }) => {
      const grant = addClaudeGrant(config, { label: "Work" });
      const inspection = inspectClaudeGrants(config, {
        realClaudeKind: "native",
        platform: "linux",
        grantStatusInspector: () => ({ state: "ok" }),
      });
      expect(inspection.grants).toHaveLength(1);
      expect(inspection.grants[0]).toMatchObject({
        id: grant.id,
        configDirConfined: true,
        markerBound: true,
        dangling: false,
        credentialState: "ok",
        credentialOrigin: "file_scoped",
      });
      expect(inspection.scopeAssumptions).toHaveLength(1);
    });
  });

  test("darwin uses the injected scoped inspector and never exposes a Keychain service or value", () => {
    withGrantHome(({ config }) => {
      const grant = addClaudeGrant(config, { label: "Keychain" });
      let calls = 0;
      const inspection = inspectClaudeGrants(config, {
        realClaudeKind: "native",
        platform: "darwin",
        grantStatusInspector: (_config, inspectedGrant) => {
          calls++;
          expect(inspectedGrant.id).toBe(grant.id);
          return { state: "none" };
        },
      });
      expect(calls).toBe(1);
      expect(inspection.grants[0]).toMatchObject({
        credentialOrigin: "keychain_scoped",
        credentialState: "none",
        dangling: false,
      });
      expect(JSON.stringify(inspection.grants[0])).not.toContain("Claude Code-credentials");
    });
  });

  test("flags a dangling grant whose scoped dir is missing", () => {
    withGrantHome(({ config }) => {
      const grant = addClaudeGrant(config, { label: "Temp" });
      rmSync(grant.configDir, { recursive: true, force: true });
      const inspection = inspectClaudeGrants(config, { realClaudeKind: "native", platform: "linux" });
      expect(inspection.grants[0]).toMatchObject({ dangling: true, credentialState: "none" });
      expect(buildFindings(reportWithGrants(inspection)).map(f => f.code)).toContain("claude_grant_dangling");
    });
  });

  test("flags an unreadable scoped credential without emitting a value", () => {
    withGrantHome(({ config }) => {
      addClaudeGrant(config, { label: "Unreadable" });
      const inspection = inspectClaudeGrants(config, {
        realClaudeKind: "native",
        platform: "linux",
        grantStatusInspector: () => ({ state: "unreadable" }),
      });
      expect(inspection.grants[0]!.credentialState).toBe("unreadable");
      expect(buildFindings(reportWithGrants(inspection)).map(f => f.code)).toContain("claude_grant_unreadable");
    });
  });

  test("flags a provider bound to a missing grant (dangling binding)", () => {
    withGrantHome(({ config }) => {
      config.providers.anthropic = { adapter: "anthropic", baseUrl: "https://api.anthropic.com", authMode: "claude-grant", claudeGrantId: "cg_missing99" };
      const inspection = inspectClaudeGrants(config, { realClaudeKind: "native", platform: "linux" });
      expect(inspection.danglingProviderBindings).toEqual([{ provider: "anthropic", grantId: "cg_missing99" }]);
      expect(buildFindings(reportWithGrants(inspection)).map(f => f.code)).toContain("claude_grant_provider_dangling");
    });
  });

  test("reports native auth env conflicts by NAME only and never leaks the value", () => {
    withGrantHome(({ config }) => {
      addClaudeGrant(config, { label: "EnvConflict" });
      const inspection = inspectClaudeGrants(config, { realClaudeKind: "native", platform: "linux", env: { ANTHROPIC_AUTH_TOKEN: "sk-super-secret", ANTHROPIC_API_KEY: "" } });
      expect(inspection.nativeAuthEnvConflicts).toEqual(["ANTHROPIC_AUTH_TOKEN"]);
      const snapshot = JSON.stringify(sanitizeClaudeDoctorReport(reportWithGrants(inspection)));
      expect(snapshot).toContain("ANTHROPIC_AUTH_TOKEN");
      expect(snapshot).not.toContain("sk-super-secret");
      expect(buildFindings(reportWithGrants(inspection)).map(f => f.code)).toContain("claude_grant_native_auth_env_conflict");
    });
  });

  test("sanitized grant inspection never leaks the grant config dir or home path", () => {
    withGrantHome(({ config, home }) => {
      const grant = addClaudeGrant(config, { label: "NoLeak" });
      const inspection = inspectClaudeGrants(config, { realClaudeKind: "native", platform: "linux", grantStatusInspector: () => ({ state: "ok" }) });
      const snapshot = JSON.stringify(sanitizeClaudeDoctorReport(reportWithGrants(inspection)));
      expect(snapshot).not.toContain(grant.configDir);
      expect(snapshot).not.toContain(home);
    });
  });

  test("does not report grant env conflicts or scope assumptions when there is no grant surface", () => {
    withGrantHome(({ config }) => {
      const inspection = inspectClaudeGrants(config, { realClaudeKind: "native", platform: "linux", env: { ANTHROPIC_AUTH_TOKEN: "sk-x" } });
      expect(inspection.grants).toEqual([]);
      expect(inspection.nativeAuthEnvConflicts).toEqual([]);
      expect(inspection.scopeAssumptions).toEqual([]);
    });
  });
});
