import { afterEach, describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdtempSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import { claudeLauncherFileName, findRealClaudeExecutable, plannedClaudeLaunchers, profileForLauncherName, removeClaudeLauncherShims, runClaudeLauncherProcess, runClaudeProfile, runNativeClaude, syncClaudeLauncherShims } from "../src/claude-launchers";
import type { RunClaudeProfileOptions } from "../src/claude-launchers";
import type { ClaudeProfileRecord, FrogConfig } from "../src/types";

const originalEnv = { ...process.env };

/** Portable Claude executable fixture name: bare `claude` on POSIX, PATHEXT-suffixed on Windows. */
const CLAUDE_EXE = process.platform === "win32" ? "claude.exe" : "claude";

afterEach(() => {
  for (const key of ["FROGPROGSY_HOME", "PATH", "FROGP_REAL_CLAUDE"] as const) {
    const value = originalEnv[key];
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
});

function config(): FrogConfig {
  return {
    port: 10100,
    defaultProvider: "anthropic",
    providers: {
      anthropic: { adapter: "anthropic", baseUrl: "https://api.anthropic.com", authMode: "forward", defaultModel: "claude-sonnet-4-6" },
    },
    claudeProfiles: {
      schemaVersion: 1,
      defaultProfileId: "cp_default",
      profiles: [
        { id: "cp_default", name: "Default Claude Code", claudeHome: "/tmp/.claude" },
        { id: "cp_work", name: "anthropic-work", claudeHome: "/tmp/.claude-work" },
        { id: "cp_personal", name: "Personal", claudeHome: "/tmp/.claude-personal" },
      ],
    },
  };
}

function executable(path: string, content = "#!/bin/sh\nexit 0\n") {
  writeFileSync(path, content, "utf8");
  chmodSync(path, 0o755);
}

describe("Claude launchers", () => {
  test("plans plain claude plus home/profile aliases", () => {
    const plan = plannedClaudeLaunchers(config());
    expect(plan.launchers.map(entry => entry.name).sort()).toEqual([
      "claude",
      "claude-anthropic-work",
      "claude-default",
      "claude-personal",
      "claude-work",
    ]);
  });

  test("writes managed shims with a pinned frogp command and the real Claude binary", () => {
    const home = mkdtempSync(join(tmpdir(), "frog-launchers-"));
    const realBin = join(home, "real-bin");
    const cmuxBin = join(home, "cmux-cli-shims");
    const fakeFrogp = join(home, process.platform === "win32" ? "fake-frogp.cmd" : "fake-frogp");
    const frogpOut = join(home, "frogp-args.txt");
    mkdirSync(realBin);
    mkdirSync(cmuxBin);
    executable(join(realBin, CLAUDE_EXE));
    executable(join(cmuxBin, CLAUDE_EXE));
    executable(
      fakeFrogp,
      process.platform === "win32"
        ? '@echo off\r\n> "%FROGP_OUT%" echo %FROGP_REAL_CLAUDE%\r\n:args\r\nif "%~1"=="" goto done\r\n>> "%FROGP_OUT%" echo %~1\r\nshift\r\ngoto args\r\n:done\r\n'
        : "#!/bin/sh\nprintf '%s\\n' \"$FROGP_REAL_CLAUDE\" > \"$FROGP_OUT\"\nfor arg in \"$@\"; do printf '%s\\n' \"$arg\" >> \"$FROGP_OUT\"; done\n",
    );
    process.env.FROGPROGSY_HOME = join(home, "frog");
    process.env.PATH = `${cmuxBin}${delimiter}${realBin}`;
    delete process.env.FROGP_REAL_CLAUDE;
    const realClaude = realpathSync.native(join(realBin, CLAUDE_EXE));
    const legacyPersonal = join(process.env.FROGPROGSY_HOME, "bin", "claude-personal");
    if (process.platform === "win32") {
      mkdirSync(join(process.env.FROGPROGSY_HOME, "bin"), { recursive: true });
      writeFileSync(legacyPersonal, "# Generated by frogprogsy\n", "utf8");
    }

    const result = syncClaudeLauncherShims(config(), { frogpCommand: [fakeFrogp] });

    expect(result.realClaude).toBe(realClaude);
    expect(result.frogpCommand).toEqual([fakeFrogp]);
    expect(result.launchers.some(entry => entry.name === "claude-personal" && entry.profileId === "cp_personal")).toBe(true);
    const personal = join(result.binDir, claudeLauncherFileName("claude-personal"));
    expect(existsSync(personal)).toBe(true);
    if (process.platform === "win32") expect(existsSync(legacyPersonal)).toBe(false);
    const script = readFileSync(personal, "utf8");
    expect(script).toContain("Generated by frogprogsy");
    if (process.platform === "win32") {
      expect(script).toContain(`set "FROGP_REAL_CLAUDE=${realClaude}"`);
      expect(script).toContain(`"${fakeFrogp}" "claude" "run" "cp_personal" "--" %*`);
      expect(script).not.toContain("#!/bin/sh");
    } else {
      expect(script).toContain(`FROGP_REAL_CLAUDE='${realClaude}'`);
      expect(script).toContain(`exec '${fakeFrogp}' 'claude' 'run' 'cp_personal' '--' "$@"`);
      expect(script).not.toContain("exec frogp ");
    }
    const executed = process.platform === "win32"
      ? spawnSync(`"${personal}" --version`, {
          shell: true,
          env: { ...process.env, FROGP_OUT: frogpOut },
          encoding: "utf8",
        })
      : spawnSync(personal, ["--version"], {
          env: { ...process.env, FROGP_OUT: frogpOut, PATH: "/usr/bin:/bin" },
          encoding: "utf8",
        });
    expect(executed.status).toBe(0);
    expect(readFileSync(frogpOut, "utf8").trim().split(/\r?\n/)).toEqual([
      realClaude,
      "claude",
      "run",
      "cp_personal",
      "--",
      "--version",
    ]);

    const removed = removeClaudeLauncherShims();
    expect(removed.removed).toContain("claude-personal");
    expect(existsSync(personal)).toBe(false);
    rmSync(home, { recursive: true, force: true });
  });

  test("findRealClaudeExecutable skips a source-form launcher from another worktree and returns the next real claude", () => {
    const root = mkdtempSync(join(tmpdir(), "frog-realclaude-"));
    // A sibling worktree's source launcher: no generated marker, but delegates to runClaudeLauncherProcess.
    const worktreeSrc = join(root, "other-worktree", "src");
    const realDir = join(root, "realbin");
    mkdirSync(worktreeSrc, { recursive: true });
    mkdirSync(realDir, { recursive: true });
    executable(
      join(worktreeSrc, CLAUDE_EXE),
      '#!/usr/bin/env bun\nimport { runClaudeLauncherProcess } from "./claude-launchers";\nrunClaudeLauncherProcess(process.argv.slice(2), "claude");\n',
    );
    executable(join(realDir, CLAUDE_EXE));
    const realClaude = realpathSync.native(join(realDir, CLAUDE_EXE));

    process.env.FROGPROGSY_HOME = join(root, "frog");
    process.env.PATH = `${worktreeSrc}${delimiter}${realDir}`;
    delete process.env.FROGP_REAL_CLAUDE;

    // The source launcher sorts first on PATH; the resolver must skip it and return the genuine binary.
    expect(findRealClaudeExecutable()).toBe(realClaude);
    rmSync(root, { recursive: true, force: true });
  });
});
const SENTINEL_TOKEN = "local-frogprogsy";

const gatewayProfile: ClaudeProfileRecord = { id: "cp_work", name: "anthropic-work", claudeHome: "/tmp/.claude-work" };

function refreshFake(order: string[], failWith?: string): NonNullable<RunClaudeProfileOptions["refreshCatalog"]> {
  return (async () => {
    order.push("refresh");
    if (failWith) throw new Error(failWith);
    return { added: 0, path: "/catalog", catalogExists: false, cacheSynced: false, gatewayCache: { status: "skipped" as const }, warnings: [] };
  }) as unknown as NonNullable<RunClaudeProfileOptions["refreshCatalog"]>;
}

function spawnFake(order: string[], capture: { env?: NodeJS.ProcessEnv }): NonNullable<RunClaudeProfileOptions["spawn"]> {
  return ((_cmd: string, _args: readonly string[], opts: { env?: NodeJS.ProcessEnv }) => {
    order.push("spawn");
    capture.env = opts.env;
    return { status: 0, signal: null } as unknown as ReturnType<typeof spawnSync>;
  }) as unknown as NonNullable<RunClaudeProfileOptions["spawn"]>;
}

function exitFake(capture: { code?: number }): NonNullable<RunClaudeProfileOptions["exit"]> {
  return ((code: number) => { capture.code = code; }) as unknown as NonNullable<RunClaudeProfileOptions["exit"]>;
}

describe("runClaudeProfile carrier + pre-launch cache", () => {
  afterEach(() => {
    const value = originalEnv.ANTHROPIC_AUTH_TOKEN;
    if (value === undefined) delete process.env.ANTHROPIC_AUTH_TOKEN;
    else process.env.ANTHROPIC_AUTH_TOKEN = value;
  });

  test("gateway launch defaults to the token-free carrier and strips any inherited sentinel token", async () => {
    process.env.ANTHROPIC_AUTH_TOKEN = SENTINEL_TOKEN;
    const order: string[] = [];
    const captured: { env?: NodeJS.ProcessEnv } = {};
    const exit: { code?: number } = {};
    await runClaudeProfile(gatewayProfile, config(), ["--version"], {
      gateway: true,
      realClaude: "/usr/bin/true",
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, captured),
      exit: exitFake(exit),
    });
    expect(captured.env?.ANTHROPIC_BASE_URL).toMatch(/^http:\/\/localhost:/);
    expect(captured.env?.CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY).toBe("1");
    expect(captured.env?.ANTHROPIC_AUTH_TOKEN).toBeUndefined();
    expect(exit.code).toBe(0);
  });

  test("gateway launch injects the sentinel token only on explicit rollback", async () => {
    const cfg: FrogConfig = { ...config(), gatewayAuthCarrier: "sentinel" };
    const captured: { env?: NodeJS.ProcessEnv } = {};
    await runClaudeProfile(gatewayProfile, cfg, [], {
      gateway: true,
      realClaude: "/usr/bin/true",
      refreshCatalog: refreshFake([]),
      spawn: spawnFake([], captured),
      exit: exitFake({}),
    });
    expect(captured.env?.ANTHROPIC_AUTH_TOKEN).toBe(SENTINEL_TOKEN);
  });

  test("refreshes the profile picker cache before spawning the gateway Claude", async () => {
    const order: string[] = [];
    await runClaudeProfile(gatewayProfile, config(), [], {
      gateway: true,
      realClaude: "/usr/bin/true",
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, {}),
      exit: exitFake({}),
    });
    expect(order).toEqual(["refresh", "spawn"]);
  });

  test("a transient refresh failure warns without leaking secrets and still launches", async () => {
    const order: string[] = [];
    const exit: { code?: number } = {};
    const warnings: string[] = [];
    const originalWarn = console.warn;
    console.warn = (...args: unknown[]) => { warnings.push(args.map(String).join(" ")); };
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: true,
        realClaude: "/usr/bin/true",
        refreshCatalog: refreshFake(order, "boom /Users/secret/.claude token=sk-leaked"),
        spawn: spawnFake(order, {}),
        exit: exitFake(exit),
      });
    } finally {
      console.warn = originalWarn;
    }
    expect(order).toEqual(["refresh", "spawn"]);
    expect(exit.code).toBe(0);
    expect(warnings.length).toBe(1);
    expect(warnings[0]).toContain("cp_work");
    expect(warnings[0]).not.toContain("sk-leaked");
    expect(warnings[0]).not.toContain("/Users/secret/.claude");
  });

  test("a returned cache failure warns without exposing provider detail and still launches", async () => {
    const order: string[] = [];
    const warnings: string[] = [];
    const originalWarn = console.warn;
    console.warn = (...args: unknown[]) => { warnings.push(args.map(String).join(" ")); };
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: true,
        realClaude: "/usr/bin/true",
        refreshCatalog: (async () => {
          order.push("refresh");
          return {
            added: 0,
            path: "/private/catalog",
            catalogExists: false,
            cacheSynced: false,
            gatewayCache: { status: "failed" as const, warning: "credential sk-secret failed" },
            warnings: ["credential sk-secret failed"],
          };
        }) as NonNullable<RunClaudeProfileOptions["refreshCatalog"]>,
        spawn: spawnFake(order, {}),
        exit: exitFake({}),
      });
    } finally {
      console.warn = originalWarn;
    }
    expect(order).toEqual(["refresh", "spawn"]);
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toContain("cp_work");
    expect(warnings[0]).toContain("when available");
    expect(warnings[0]).not.toContain("sk-secret");
    expect(warnings[0]).not.toContain("/private/catalog");
  });

  test("native (non-gateway) launch never refreshes the catalog and drops gateway env", async () => {
    const order: string[] = [];
    const captured: { env?: NodeJS.ProcessEnv } = {};
    await runClaudeProfile(gatewayProfile, config(), [], {
      gateway: false,
      realClaude: "/usr/bin/true",
      refreshCatalog: refreshFake(order),
      spawn: spawnFake(order, captured),
      exit: exitFake({}),
    });
    expect(order).toEqual(["spawn"]);
    expect(captured.env?.ANTHROPIC_BASE_URL).toBeUndefined();
    expect(captured.env?.CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY).toBeUndefined();
    expect(captured.env?.CLAUDE_CONFIG_DIR).toBe("/tmp/.claude-work");
  });
});
const LAUNCHER_FAILURE_MESSAGE = "frogprogsy: failed to launch the Claude executable.";

function spawnReturning(result: Partial<ReturnType<typeof spawnSync>>): NonNullable<RunClaudeProfileOptions["spawn"]> {
  return (() => result as unknown as ReturnType<typeof spawnSync>) as unknown as NonNullable<RunClaudeProfileOptions["spawn"]>;
}

function captureConsoleError(): { messages: string[]; restore: () => void } {
  const messages: string[] = [];
  const original = console.error;
  console.error = (...args: unknown[]) => { messages.push(args.map(String).join(" ")); };
  return { messages, restore: () => { console.error = original; } };
}

function spawnError(code: string, path: string): NodeJS.ErrnoException {
  return Object.assign(new Error(`spawn ${path} ${code}`), { code, path, syscall: `spawn ${path}` });
}

describe("launcher spawn failure exit codes", () => {
  test("runClaudeProfile maps an ENOENT spawn failure to 127 with a fixed, redacted diagnostic", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), ["--version"], {
        gateway: false,
        realClaude: "/opt/homebrew/bin/claude",
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("ENOENT", "/opt/homebrew/bin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(127);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/opt/homebrew/bin/claude");
    expect(err.messages[0]).not.toContain("ENOENT");
  });

  test("runClaudeProfile maps an EACCES spawn failure to 1 without leaking the path", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/tmp/blocked/claude",
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("EACCES", "/tmp/blocked/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/tmp/blocked/claude");
  });

  test("runClaudeProfile: a signal kill without a status never surfaces as exit 0", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/usr/bin/true",
        spawn: spawnReturning({ status: null, signal: "SIGKILL" }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toHaveLength(0);
  });

  test("runClaudeProfile: an ordinary non-zero status propagates unchanged", async () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      await runClaudeProfile(gatewayProfile, config(), [], {
        gateway: false,
        realClaude: "/usr/bin/true",
        spawn: spawnReturning({ status: 3, signal: null }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(3);
    expect(err.messages).toHaveLength(0);
  });

  test("runNativeClaude maps an ENOENT spawn failure to 127 with a redacted diagnostic", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude(["--help"], {
        realClaude: "/usr/local/bin/claude",
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("ENOENT", "/usr/local/bin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(127);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
    expect(err.messages[0]).not.toContain("/usr/local/bin/claude");
  });

  test("runNativeClaude maps an EACCES spawn failure to 1", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude([], {
        realClaude: "/sbin/claude",
        spawn: spawnReturning({ status: null, signal: null, error: spawnError("EACCES", "/sbin/claude") }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(1);
    expect(err.messages).toEqual([LAUNCHER_FAILURE_MESSAGE]);
  });

  test("runNativeClaude: an ordinary status propagates unchanged (including 0)", () => {
    const exit: { code?: number } = {};
    const err = captureConsoleError();
    try {
      runNativeClaude([], {
        realClaude: "/usr/bin/true",
        spawn: spawnReturning({ status: 0, signal: null }),
        exit: exitFake(exit),
      });
    } finally {
      err.restore();
    }
    expect(exit.code).toBe(0);
    expect(err.messages).toHaveLength(0);
  });
});

describe("launcher alias routing", () => {
  test("an exact planned launcher name routes to its exact profileId", () => {
    expect(profileForLauncherName(config(), "claude-work").id).toBe("cp_work");
    expect(profileForLauncherName(config(), "claude-anthropic-work").id).toBe("cp_work");
    expect(profileForLauncherName(config(), "claude-personal").id).toBe("cp_personal");
    expect(profileForLauncherName(config(), "claude-default").id).toBe("cp_default");
  });

  test("plain claude routes to the default profile", () => {
    expect(profileForLauncherName(config(), "claude").id).toBe("cp_default");
  });

  test("an unknown or stale alias throws Unknown Claude Code home instead of silently using the default profile", () => {
    expect(() => profileForLauncherName(config(), "claude-ghost")).toThrow(/Unknown Claude Code home/);
    expect(() => profileForLauncherName(config(), "claude-cp_removed")).toThrow(/Unknown Claude Code home/);
    let routed: string | undefined;
    try {
      routed = profileForLauncherName(config(), "claude-ghost").id;
    } catch {
      routed = undefined;
    }
    expect(routed).toBeUndefined();
  });

  test("plain claude with no config falls through to the native passthrough", async () => {
    const home = mkdtempSync(join(tmpdir(), "frog-nolcfg-"));
    process.env.FROGPROGSY_HOME = join(home, "frog");
    const captured: string[][] = [];
    const runNative = ((claudeArgs: string[]) => { captured.push(claudeArgs); }) as unknown as (claudeArgs: string[]) => never;
    try {
      await runClaudeLauncherProcess(["--version"], "claude", { runNative });
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
    expect(captured).toEqual([["--version"]]);
  });
});
