import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join, sep } from "node:path";
import { __requestLogTest } from "../src/server";
import type { FrogConfig, FrogProviderConfig } from "../src/types";

// ── isolated env ────────────────────────────────────────────────────────────
// FROGPROGSY_HOME is redirected to a throwaway temp dir so grant create/remove never touch a real
// frogprogsy home, native Claude homes, or the global Keychain. A fake "claude" file stands in for a
// REAL executable so guided-login command building succeeds without a Claude install / any network.

let prevHome: string | undefined;
let prevNoWrites: string | undefined;
let prevRealClaude: string | undefined;
let prevUserHome: string | undefined;
let testHome = "";
let realHome = "";
let exeDir = "";
let fakeClaude = "";
let shimClaude = "";

const LAUNCHER_MARKER = "Generated by frogprogsy";
function executableFixtureName(base: string): string {
  return process.platform === "win32" ? `${base}.cmd` : base;
}

function homeTokenizeExpected(path: string): string {
  const home = (process.env.HOME?.trim() || homedir() || "").replace(/[/\\]+$/, "");
  return home && (path === home || path.startsWith(`${home}${sep}`))
    ? `$HOME${path.slice(home.length)}`
    : path;
}

function setup(): void {
  prevHome = process.env.FROGPROGSY_HOME;
  prevNoWrites = process.env.FROGPROGSY_NO_CLAUDE_WRITES;
  prevRealClaude = process.env.FROGP_REAL_CLAUDE;
  prevUserHome = process.env.HOME;
  // Make the throwaway OS temp root the test's logical $HOME. This positively exercises path
  // tokenization on every platform without writing anything to the user's real home.
  process.env.HOME = realpathSync.native(tmpdir());
  process.env.FROGPROGSY_NO_CLAUDE_WRITES = "1";
  // Never let a machine-local claude leak into the "no executable" fail-closed paths.
  delete process.env.FROGP_REAL_CLAUDE;

  testHome = mkdtempSync(join(tmpdir(), "frog-grant-home-"));
  process.env.FROGPROGSY_HOME = testHome;
  realHome = realpathSync.native(testHome);

  exeDir = mkdtempSync(join(tmpdir(), "frog-grant-exe-"));
  fakeClaude = join(exeDir, executableFixtureName("claude"));
  writeFileSync(fakeClaude, process.platform === "win32" ? "@echo off\r\necho fake-claude\r\n" : "#!/bin/sh\necho fake-claude\n", { mode: 0o755 });
  shimClaude = join(exeDir, executableFixtureName("claude-shim"));
  writeFileSync(
    shimClaude,
    process.platform === "win32"
      ? `@echo off\r\nrem ${LAUNCHER_MARKER} launcher\r\nclaude %*\r\n`
      : `#!/bin/sh\n# ${LAUNCHER_MARKER} launcher\nexec claude "$@"\n`,
    { mode: 0o755 },
  );

  __requestLogTest.clear();
}

function teardown(): void {
  if (prevHome === undefined) delete process.env.FROGPROGSY_HOME;
  else process.env.FROGPROGSY_HOME = prevHome;
  if (prevNoWrites === undefined) delete process.env.FROGPROGSY_NO_CLAUDE_WRITES;
  else process.env.FROGPROGSY_NO_CLAUDE_WRITES = prevNoWrites;
  if (prevRealClaude === undefined) delete process.env.FROGP_REAL_CLAUDE;
  else process.env.FROGP_REAL_CLAUDE = prevRealClaude;
  if (prevUserHome === undefined) delete process.env.HOME;
  else process.env.HOME = prevUserHome;
  for (const dir of [testHome, exeDir]) if (dir) rmSync(dir, { recursive: true, force: true });
  testHome = "";
  exeDir = "";
  __requestLogTest.clear();
}

beforeEach(setup);
afterEach(teardown);

function config(): FrogConfig {
  return {
    port: 10100,
    defaultProvider: "anthropic",
    providers: {
      anthropic: { adapter: "anthropic", baseUrl: "https://api.anthropic.com", authMode: "forward", defaultModel: "claude-sonnet-4-6" },
    },
  };
}
function bindGrantProvider(cfg: FrogConfig, name: string, grantId: string, baseUrl = "https://api.anthropic.com"): void {
  cfg.providers[name] = {
    adapter: "anthropic",
    baseUrl,
    authMode: "claude-grant",
    claudeGrantId: grantId,
    defaultModel: "claude-sonnet-4-6",
  };
}


interface CallOpts {
  cfg: FrogConfig;
  body?: unknown;
  origin?: string | null;
  host?: string;
  grantDeps?: Record<string, unknown>;
  saveConfig?: (cfg: FrogConfig) => void;
}

async function manage(method: string, path: string, opts: CallOpts): Promise<Response> {
  const host = opts.host ?? "localhost";
  const headers: Record<string, string> = {};
  if (opts.origin !== null) headers.Origin = opts.origin ?? "http://localhost:10100";
  if (opts.body !== undefined) headers["content-type"] = "application/json";
  const url = `http://${host}${path}`;
  const req = new Request(url, {
    method,
    headers,
    ...(opts.body !== undefined ? { body: JSON.stringify(opts.body) } : {}),
  });
  const res = await __requestLogTest.handleManagementAPI(req, new URL(url), opts.cfg, {
    saveConfig: opts.saveConfig ?? (() => {}),
    ...(opts.grantDeps ? { claudeGrants: opts.grantDeps } : {}),
  });
  expect(res).not.toBeNull();
  return res!;
}

/** Assert no credential material leaked into a serialized local-management response. */
function expectNoLeaks(serialized: string): void {
  expect(serialized).not.toContain(LAUNCHER_MARKER);
  expect(serialized).not.toContain("claudeAiOauth");
  expect(serialized).not.toContain("refreshToken");
  expect(serialized).not.toContain("accessToken");
}

async function createGrant(cfg: FrogConfig, label: string, grantDeps?: Record<string, unknown>): Promise<{ id: string; body: any }> {
  const res = await manage("POST", "/api/claude-grants", { cfg, body: { label }, grantDeps: grantDeps ?? { realClaude: fakeClaude } });
  expect(res.status).toBe(201);
  const body = await res.json();
  return { id: body.grant.id, body };
}

describe("claude-grant management API — local-origin protection", () => {
  test("GET/POST/DELETE/probe are all blocked from a cross-origin caller", async () => {
    const cfg = config();
    for (const [method, path] of [["GET", "/api/claude-grants"], ["POST", "/api/claude-grants"], ["DELETE", "/api/claude-grants/cg_abcdef"], ["POST", "/api/claude-grants/cg_abcdef/probe"]] as const) {
      const res = await manage(method, path, { cfg, origin: "https://evil.example", body: method === "POST" ? {} : undefined });
      expect(res.status).toBe(403);
    }
  });

  test("originless mutation must still target a loopback URL", async () => {
    const cfg = config();
    const res = await manage("GET", "/api/claude-grants", { cfg, origin: null, host: "evil.example" });
    expect(res.status).toBe(403);
  });

  test("loopback origin is allowed", async () => {
    const cfg = config();
    const res = await manage("GET", "/api/claude-grants", { cfg });
    expect(res.status).toBe(200);
  });
});

describe("claude-grant management API — create / list / delete", () => {
  test("POST creates a grant + real-executable login guidance; GET lists it; DELETE removes it", async () => {
    const cfg = config();
    const { id, body } = await createGrant(cfg, "Work");

    expect(id).toMatch(/^cg_[a-z0-9]{6,}$/);
    expect(body.grant.label).toBe("Work");
    expect(body.boundProviders).toEqual([]);
    // Guided-login data is intentionally redacted for display: paths under the user home are emitted as
    // $HOME tokens, while system/temp paths outside it stay absolute. It never falls back to bare `claude`.
    expect(body.setup.argv[0]).toStartWith("$HOME");
    expect(body.setup.argv[0]).toBe(homeTokenizeExpected(realpathSync.native(fakeClaude)));
    expect(body.setup.argv).toContain("login");
    expect(body.setup.env.CLAUDE_CONFIG_DIR).toBe(homeTokenizeExpected(join(realHome, "claude-grants", id)));
    expect(body.setup.env.CLAUDE_CONFIG_DIR).toStartWith("$HOME");
    expect(body.setup.command).toContain("CLAUDE_CONFIG_DIR=");
    const executableDisplay = homeTokenizeExpected(realpathSync.native(fakeClaude));
    expect(body.setup.command).toContain(
      process.platform === "win32" ? executableDisplay : executableDisplay.replace(/\\/g, "\\\\"),
    );
    expect(body.setup.expectedService).toStartWith("Claude Code-credentials-");
    expect(body.setup.expectedService).not.toBe("Claude Code-credentials");
    expectNoLeaks(JSON.stringify(body));

    const listRes = await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude } });
    expect(listRes.status).toBe(200);
    const list = await listRes.json();
    expect(list.grants).toHaveLength(1);
    expect(list.grants[0]).toMatchObject({
      id,
      label: "Work",
      boundProviders: [],
      realClaudeReady: true,
    });
    expect(list.grants[0].executable).toBeUndefined();
    expect(list.grants[0].service).toBeUndefined();
    expect(list.realClaude.name).toStartWith("$HOME");
    expect(list.realClaude).toEqual({ ready: true, name: homeTokenizeExpected(realpathSync.native(fakeClaude)) });
    expectNoLeaks(JSON.stringify(list));

    const delRes = await manage("DELETE", `/api/claude-grants/${id}`, { cfg, grantDeps: { deleteCredential: () => {} } });
    expect(delRes.status).toBe(200);
    const del = await delRes.json();
    expect(del.removed.id).toBe(id);
    expect(del.danglingProviders).toEqual([]);

    const afterRes = await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude } });
    expect((await afterRes.json()).grants).toHaveLength(0);
  });

  test("POST rejects an empty label with 400", async () => {
    const cfg = config();
    const res = await manage("POST", "/api/claude-grants", { cfg, body: { label: "   " }, grantDeps: { realClaude: fakeClaude } });
    expect(res.status).toBe(400);
  });

  test("DELETE of an unknown / malformed id is 404", async () => {
    const cfg = config();
    expect((await manage("DELETE", "/api/claude-grants/cg_missing99", { cfg })).status).toBe(404);
    expect((await manage("DELETE", "/api/claude-grants/not-a-grant", { cfg })).status).toBe(404);
  });
});

describe("claude-grant management API — managed/bare executable rejection", () => {
  test("a managed frogprogsy launcher shim is rejected 409 and the grant is rolled back", async () => {
    const cfg = config();
    const res = await manage("POST", "/api/claude-grants", { cfg, body: { label: "Shim" }, grantDeps: { realClaude: shimClaude } });
    expect(res.status).toBe(409);
    const body = await res.json();
    expect(body.error.code).toBe("managed_executable_rejected");
    expectNoLeaks(JSON.stringify(body));
    // Rolled back: no orphan grant persists.
    const list = await (await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude } })).json();
    expect(list.grants).toHaveLength(0);
  });

  test("a bare 'claude' resolution is rejected 409 (interceptable by a shim) and rolled back", async () => {
    const cfg = config();
    const res = await manage("POST", "/api/claude-grants", { cfg, body: { label: "Bare" }, grantDeps: { resolveRealClaude: () => "claude" } });
    expect(res.status).toBe(409);
    const body = await res.json();
    expect(body.error.code).toBe("real_executable_unavailable");
    const list = await (await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude } })).json();
    expect(list.grants).toHaveLength(0);
  });
});

describe("claude-grant management API — status (fail-closed) + no secret leak", () => {
  test("injected inspector drives the canonical state/expiresAt view without source internals", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "Status");
    const expiresAt = Date.now() + 3_600_000;
    const res = await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude, inspectStatus: () => ({ state: "ok", expiresAt }) } });
    const grant = (await res.json()).grants.find((g: any) => g.id === id);
    expect(grant.state).toBe("ok");
    expect(grant.statusSource).toBeUndefined();
    expect(grant.expiresAt).toBe(new Date(expiresAt).toISOString());
    expect(grant.statusError).toBeUndefined();
  });

  test("an inspector that throws fails closed to unreadable/status_unavailable", async () => {
    const cfg = config();
    await createGrant(cfg, "Throws");
    const res = await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude, inspectStatus: () => { throw new Error("keychain unreachable"); } } });
    const grant = (await res.json()).grants[0];
    expect(grant.state).toBe("unreadable");
    expect(grant.statusSource).toBeUndefined();
    expect(grant.statusError).toBe("status_unavailable");
  });

  test("an inspector returning an unknown shape fails closed to status_unavailable", async () => {
    const cfg = config();
    await createGrant(cfg, "Garbage");
    const res = await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude, inspectStatus: () => ({ state: "bogus" }) } });
    const grant = (await res.json()).grants[0];
    expect(grant.state).toBe("unreadable");
    expect(grant.statusError).toBe("status_unavailable");
  });

  test("no injected inspector: state stays inside the enum and only the validated executable path is exposed", async () => {
    const cfg = config();
    await createGrant(cfg, "NoInspector");
    const res = await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude } });
    const list = await res.json();
    expect(["none", "ok", "expiring", "reauth_required", "unreadable"]).toContain(list.grants[0].state);
    expect(list.realClaude.name).toStartWith("$HOME");
    expect(list.realClaude.name).toBe(homeTokenizeExpected(realpathSync.native(fakeClaude)));
    expectNoLeaks(JSON.stringify(list));
  });
});

describe("claude-grant management API — probe tier consent", () => {
  test("tier-1 returns local-only meta with no network and no secrets", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "Probe1");
    const res = await manage("POST", `/api/claude-grants/${id}/probe`, { cfg, body: { tier: 1 }, grantDeps: { realClaude: fakeClaude, inspectStatus: () => ({ state: "ok" }) } });
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body.tier).toBe(1);
    expect(body.network).toBe(false);
    expect(body.state).toBe("ok");
    expect(body.executable.ready).toBe(true);
    expect(body.service).toStartWith("Claude Code-credentials-");
    expectNoLeaks(JSON.stringify(body));
  });

  test("tier-2 without confirm is 400 with ToS/account/quota guidance", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "Probe2");
    const res = await manage("POST", `/api/claude-grants/${id}/probe`, { cfg, body: { tier: 2 }, grantDeps: { realClaude: fakeClaude } });
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error.code).toBe("confirmation_required");
    expect(body.error.message).toContain("Terms of Service");
    expect(body.error.message.toLowerCase()).toContain("quota");
  });

  test("tier-2 with confirm but no bound provider fails closed before the live helper", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "ProbeUnbound");
    let calls = 0;
    const res = await manage("POST", `/api/claude-grants/${id}/probe`, {
      cfg,
      body: { tier: 2, confirm: true },
      grantDeps: { realClaude: fakeClaude, liveProbe: () => { calls++; throw new Error("must not run"); } },
    });
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error.code).toBe("provider_required");
    expect(calls).toBe(0);
  });

  test("tier-2 with confirm + one bound official provider returns only redacted live result fields", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "ProbeLive");
    bindGrantProvider(cfg, "anthropic-grant", id);
    let received: unknown[] = [];
    const res = await manage("POST", `/api/claude-grants/${id}/probe`, {
      cfg,
      body: { tier: 2, confirm: true },
      grantDeps: {
        realClaude: fakeClaude,
        liveProbe: (receivedConfig: FrogConfig, name: string, provider: FrogProviderConfig) => {
          received = [receivedConfig, name, provider];
          return {
            status: 200,
            modelCount: 2,
            modelId: "claude-sonnet-4-6",
            messageStatus: 200,
            tokenFingerprint: { sha256_8: "deadbeef", length: 321 },
          };
        },
      },
    });
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(received).toEqual([cfg, "anthropic-grant", cfg.providers["anthropic-grant"]]);
    expect(body).toEqual({
      tier: 2,
      ok: true,
      status: 200,
      modelCount: 2,
      modelId: "claude-sonnet-4-6",
      messageStatus: 200,
      tokenFingerprint: { sha256_8: "deadbeef", length: 321 },
    });
    expectNoLeaks(JSON.stringify(body));
  });

  test("tier-2 rejects a non-official target before token or network access", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "ProbeInvalid");
    bindGrantProvider(cfg, "anthropic-grant", id, "https://attacker.example");
    let calls = 0;
    const res = await manage("POST", `/api/claude-grants/${id}/probe`, {
      cfg,
      body: { tier: 2, confirm: true },
      grantDeps: { realClaude: fakeClaude, liveProbe: () => { calls++; throw new Error("must not run"); } },
    });
    expect(res.status).toBe(400);
    expect((await res.json()).error.code).toBe("provider_target_invalid");
    expect(calls).toBe(0);
  });

  test("an invalid tier is rejected 400", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "ProbeTier");
    const res = await manage("POST", `/api/claude-grants/${id}/probe`, { cfg, body: { tier: 3 }, grantDeps: { realClaude: fakeClaude } });
    expect(res.status).toBe(400);
  });
});

describe("claude-grant management API — bound-provider delete (dangling, oauth cleanup untouched)", () => {
  const bindProvider = bindGrantProvider;

  test("GET reports the bound provider; unconfirmed delete is 409 with a warning", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "Bound");
    bindProvider(cfg, "anthropic-work", id);

    const list = await (await manage("GET", "/api/claude-grants", { cfg, grantDeps: { realClaude: fakeClaude } })).json();
    expect(list.grants[0].boundProviders).toEqual(["anthropic-work"]);

    const blocked = await manage("DELETE", `/api/claude-grants/${id}`, { cfg });
    expect(blocked.status).toBe(409);
    const body = await blocked.json();
    expect(body.error.code).toBe("grant_bound");
    expect(body.boundProviders).toEqual(["anthropic-work"]);
    // Nothing removed while unconfirmed.
    expect(cfg.claudeGrants?.grants.some(g => g.id === id)).toBe(true);
  });

  test("confirmed delete removes the grant, leaves the binding dangling, and never runs oauth cleanup", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "Bound2");
    bindProvider(cfg, "anthropic-work", id);

    const res = await manage("DELETE", `/api/claude-grants/${id}?confirm=true`, { cfg, grantDeps: { deleteCredential: () => {} } });
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body.removed.id).toBe(id);
    expect(body.danglingProviders).toEqual(["anthropic-work"]);
    expect(body.warning).toContain("rebound");

    // Grant gone, but the provider binding is preserved untouched (dangling, not auto-rebound/removed).
    expect(cfg.claudeGrants?.grants.some(g => g.id === id)).toBe(false);
    expect(cfg.providers["anthropic-work"]).toBeDefined();
    expect(cfg.providers["anthropic-work"].authMode).toBe("claude-grant");
    expect(cfg.providers["anthropic-work"].claudeGrantId).toBe(id);
  });

  test("unsafe marker fails preflight before scoped credential deletion", async () => {
    const cfg = config();
    const { id } = await createGrant(cfg, "Unsafe");
    const grant = cfg.claudeGrants!.grants.find(item => item.id === id)!;
    writeFileSync(join(grant.configDir, ".frogprogsy-grant.json"), JSON.stringify({
      schemaVersion: 1,
      id: "cg_other123",
      configDir: grant.configDir,
      createdAt: grant.createdAt,
    }));
    let credentialDeletes = 0;

    const res = await manage("DELETE", `/api/claude-grants/${id}`, {
      cfg,
      grantDeps: { deleteCredential: () => { credentialDeletes++; } },
    });

    expect(res.status).toBe(409);
    expect((await res.json()).error.code).toBe("grant_marker_mismatch");
    expect(credentialDeletes).toBe(0);
    expect(cfg.claudeGrants!.grants.some(item => item.id === id)).toBe(true);
  });
});
