import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { deriveJawcodeAliases } from "../src/providers/derive";

const PROVIDER_ALIASES = deriveJawcodeAliases();

type RawModel = {
  id?: string;
  contextWindow?: number;
  maxTokens?: number;
  input?: ("text" | "image")[];
  reasoning?: boolean;
  wireModelId?: string;
};

const sourcePath = process.env.JAWCODE_MODELS_JSON
  ? resolve(process.env.JAWCODE_MODELS_JSON)
  : resolve(process.cwd(), "../jawcode/packages/ai/src/models.json");
const outPath = resolve(process.cwd(), "src/generated/jawcode-model-metadata.ts");
const CONTEXT_WINDOW_OVERRIDES: Record<string, number> = {
  "anthropic/claude-sonnet-4-6": 200_000,
  "anthropic/claude-sonnet-4-6[1m]": 200_000,
};

if (!existsSync(sourcePath)) {
  throw new Error(`jawcode models.json not found: ${sourcePath}`);
}

const registry = JSON.parse(readFileSync(sourcePath, "utf-8")) as Record<string, Record<string, RawModel>>;
const allowedProviders = Array.from(new Set(Object.values(PROVIDER_ALIASES))).sort();
const lines: string[] = [];

function compactRow(values: unknown[]): unknown[] {
  while (values.length > 0 && values[values.length - 1] === undefined) values.pop();
  return values;
}

lines.push("/* eslint-disable */");
lines.push("// Generated by scripts/generate-jawcode-metadata.ts. Do not edit by hand.");
lines.push("");
lines.push("export interface JawcodeModelMetadata {");
lines.push("  provider: string;");
lines.push("  id: string;");
lines.push("  contextWindow?: number;");
lines.push("  maxTokens?: number;");
lines.push("  input?: (\"text\" | \"image\")[];");
lines.push("  reasoning?: boolean;");
lines.push("  wireModelId?: string;");
lines.push("}");
lines.push("");
lines.push("const PROVIDER_ALIASES: Record<string, string> = " + JSON.stringify(PROVIDER_ALIASES, null, 2) + " as const;");
lines.push("");
lines.push("type Row = readonly [id: string, contextWindow?: number, maxTokens?: number, input?: string, reasoning?: 0 | 1, wireModelId?: string];");
lines.push("const DATA: Record<string, readonly Row[]> = {");

for (const provider of allowedProviders) {
  const models = registry[provider] ?? {};
  const rows = Object.entries(models)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, model]) => compactRow([
      id,
      CONTEXT_WINDOW_OVERRIDES[`${provider}/${id}`] ?? model.contextWindow,
      model.maxTokens,
      Array.isArray(model.input) ? model.input.join(",") : undefined,
      model.reasoning === undefined ? undefined : (model.reasoning ? 1 : 0),
      model.wireModelId,
    ]));
  lines.push(`  ${JSON.stringify(provider)}: ${JSON.stringify(rows)},`);
}

lines.push("};");
lines.push("");
lines.push("export function resolveJawcodeProvider(provider: string): string | undefined {");
lines.push("  return PROVIDER_ALIASES[provider];");
lines.push("}");
lines.push("");
lines.push("export function getJawcodeModelMetadata(provider: string, modelId: string): JawcodeModelMetadata | undefined {");
lines.push("  const row = DATA[provider]?.find(r => r[0] === modelId);");
lines.push("  if (!row) return undefined;");
lines.push("  return rowToMetadata(provider, row);");
lines.push("}");
lines.push("");
lines.push("export function getJawcodeModelMetadataCaseInsensitive(provider: string, modelId: string): JawcodeModelMetadata | undefined {");
lines.push("  const lower = modelId.toLowerCase();");
lines.push("  const row = DATA[provider]?.find(r => r[0].toLowerCase() === lower);");
lines.push("  if (!row) return undefined;");
lines.push("  return rowToMetadata(provider, row);");
lines.push("}");
lines.push("");
lines.push("export function listJawcodeModelMetadata(provider: string): JawcodeModelMetadata[] {");
lines.push("  return (DATA[provider] ?? []).map(row => rowToMetadata(provider, row));");
lines.push("}");
lines.push("");
lines.push("function rowToMetadata(provider: string, row: Row): JawcodeModelMetadata {");
lines.push("  const [id, contextWindow, maxTokens, input, reasoning, wireModelId] = row;");
lines.push("  return {");
lines.push("    provider, id,");
lines.push("    ...(contextWindow !== undefined ? { contextWindow } : {}),");
lines.push("    ...(maxTokens !== undefined ? { maxTokens } : {}),");
lines.push("    ...(input ? { input: input.split(\",\") as (\"text\" | \"image\")[] } : {}),");
lines.push("    ...(reasoning !== undefined ? { reasoning: reasoning === 1 } : {}),");
lines.push("    ...(wireModelId !== undefined ? { wireModelId } : {}),");
lines.push("  };");
lines.push("}");
lines.push("");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n"));
console.log(`wrote ${outPath} from ${sourcePath}`);
