import { spawnSync } from "node:child_process";
import { chmodSync, closeSync, existsSync, mkdirSync, openSync, readFileSync, readSync, realpathSync, rmSync } from "node:fs";
import { basename, delimiter, dirname, join, resolve, sep } from "node:path";
import { DEFAULT_PORT, atomicWriteFile, ensureConfigDirForWrite, getConfigDir, getConfigPath, loadConfig, readActivePort, readPid } from "./config";
import { buildClaudeProfileNativeEnv, buildClaudeProfileRunEnv, ensureClaudeProfiles, managedClaudeProfiles, resolveClaudeProfile } from "./claude-profiles";
import type { ClaudeProfileRecord, FrogConfig } from "./types";

export interface ClaudeLauncherEntry {
  name: string;
  profileId: string;
  profileName: string;
  claudeHome: string;
}

export interface ClaudeLauncherSyncResult {
  binDir: string;
  realClaude: string;
  launchers: ClaudeLauncherEntry[];
  removed: string[];
  warnings: string[];
  frogpCommand: string[];
}

interface ClaudeLauncherManifest {
  schemaVersion: 1;
  generatedAt: string;
  binDir: string;
  realClaude: string;
  launchers: ClaudeLauncherEntry[];
  frogpCommand?: string[];
}

const MANIFEST_NAME = "claude-launchers.json";
const MANAGED_MARKER = "Generated by frogprogsy";
/**
 * Substring emitted by a source-form frogprogsy launcher: any `.ts` entrypoint that delegates to
 * `runClaudeLauncherProcess` is a launcher even without the generated marker (e.g. a sibling worktree's
 * `src/claude.ts`). Kept in sync with the real delegation call below.
 */
const LAUNCHER_SOURCE_MARKER = "runClaudeLauncherProcess";
/**
 * Bytes sniffed from a candidate's head. Bounded so a multi-hundred-MB native Claude binary is never
 * read in full, while still large enough to capture any launcher's shebang, generated marker, or
 * delegation call which always appear at the very top of the file.
 */
const LAUNCHER_SNIFF_BYTES = 64 * 1024;

/**
 * Windows executable suffixes supported when resolving a bare command like `claude` from PATH.
 * The deterministic order covers the forms Claude installations actually ship as: `.exe` for a
 * native binary and `.cmd`/`.bat`/`.com` for npm/npx-style shims. It intentionally does not depend
 * on machine-specific PATHEXT ordering and is consulted only on win32, leaving POSIX unchanged.
 */
export const WINDOWS_EXECUTABLE_SUFFIXES = [".exe", ".cmd", ".bat", ".com"] as const;

/**
 * On-disk file names to probe, in PATH-order preference, for a base command such as `claude`.
 * POSIX: exactly the bare name (exact behavior preserved). Windows: the PATHEXT-like suffixed forms,
 * unless `base` already carries a recognized suffix (then it is used verbatim).
 */
export function claudeExecutableCandidates(base = "claude"): string[] {
  if (process.platform !== "win32") return [base];
  const lower = base.toLowerCase();
  if (WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => lower.endsWith(suffix))) return [base];
  return WINDOWS_EXECUTABLE_SUFFIXES.map(suffix => `${base}${suffix}`);
}
/** Platform-native filename for a generated managed launcher alias. */
export function claudeLauncherFileName(name: string): string {
  return process.platform === "win32" ? `${name}.cmd` : name;
}

/** True when `path` ends with a Windows executable suffix (PATHEXT-like). Case-insensitive. */
export function hasWindowsExecutableSuffix(path: string): boolean {
  const lower = path.toLowerCase();
  return WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => lower.endsWith(suffix));
}

/**
 * True when `path`'s basename is the bare `claude` command in a platform-native executable form:
 * `claude` on any platform, plus the Windows suffixed forms (`claude.exe`/`.cmd`/`.bat`/`.com`).
 * Splits on both `/` and `\` so it matches POSIX fixtures and real Windows paths alike.
 */
export function isClaudeExecutableBasename(path: string): boolean {
  const cut = Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"));
  const base = (cut >= 0 ? path.slice(cut + 1) : path).toLowerCase();
  return base === "claude" || WINDOWS_EXECUTABLE_SUFFIXES.some(suffix => base === `claude${suffix}`);
}

export function claudeLauncherBinDir(): string {
  return join(getConfigDir(), "bin");
}

function manifestPath(): string {
  return join(getConfigDir(), MANIFEST_NAME);
}

function realpathMaybe(path: string): string {
  try { return realpathSync.native(path); } catch { return resolve(path); }
}

function isExecutableFile(path: string): boolean {
  if (!existsSync(path)) return false;
  try {
    const real = realpathMaybe(path);
    return existsSync(real);
  } catch {
    return false;
  }
}

/**
 * Shared source of truth: is `path` a frogprogsy Claude launcher of ANY form — a generated shim
 * (carries {@link MANAGED_MARKER}) or a source entrypoint that delegates to `runClaudeLauncherProcess`
 * ({@link LAUNCHER_SOURCE_MARKER}) — regardless of its worktree location or symlink chain? Only a
 * bounded head prefix is read, so a real native Claude binary is never slurped whole. Fails closed:
 * any unexpected read/I/O error is treated as "is a launcher" so a suspect candidate is skipped or
 * rejected rather than trusted. Callers pass the canonical (already realpath-resolved) path.
 */
export function isFrogprogsyClaudeLauncher(path: string): boolean {
  let fd: number | undefined;
  try {
    fd = openSync(path, "r");
    const buffer = Buffer.alloc(LAUNCHER_SNIFF_BYTES);
    const bytesRead = readSync(fd, buffer, 0, LAUNCHER_SNIFF_BYTES, 0);
    const head = buffer.toString("utf8", 0, bytesRead);
    return head.includes(MANAGED_MARKER) || head.includes(LAUNCHER_SOURCE_MARKER);
  } catch {
    return true;
  } finally {
    if (fd !== undefined) {
      try { closeSync(fd); } catch { /* best effort */ }
    }
  }
}

function currentPackageSrcDir(): string {
  return realpathMaybe(dirname(process.argv[1] ?? "."));
}

function isInside(parent: string, child: string): boolean {
  const p = realpathMaybe(parent);
  const c = realpathMaybe(child);
  return c === p || c.startsWith(`${p}${sep}`);
}

export function findRealClaudeExecutable(extraSkipDirs: string[] = []): string {
  const explicit = process.env.FROGP_REAL_CLAUDE?.trim();
  if (explicit && isExecutableFile(explicit)) return realpathMaybe(explicit);

  const skipDirs = [claudeLauncherBinDir(), currentPackageSrcDir(), ...extraSkipDirs].map(realpathMaybe);
  const candidates = claudeExecutableCandidates();
  const pathEntries = (process.env.PATH ?? "").split(delimiter).filter(Boolean);
  for (const dir of pathEntries) {
    const resolvedDir = realpathMaybe(dir);
    if (resolvedDir.includes("cmux-cli-shims")) continue;
    if (skipDirs.some(skip => resolvedDir === skip || resolvedDir.startsWith(`${skip}${sep}`))) continue;
    // Honor PATHEXT-like suffixes on Windows: probe each candidate name in preference order within
    // this dir before moving on. POSIX has a single candidate (`claude`), so behavior is unchanged.
    for (const name of candidates) {
      const candidate = join(dir, name);
      if (!isExecutableFile(candidate)) continue;
      const real = realpathMaybe(candidate);
      if (real.includes("cmux-cli-shims")) continue;
      if (skipDirs.some(skip => real === skip || real.startsWith(`${skip}${sep}`))) continue;
      if (isFrogprogsyClaudeLauncher(real)) continue;
      return real;
    }
  }
  return "claude";
}

function slugify(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-{2,}/g, "-");
}

function profileLauncherNames(profile: ClaudeProfileRecord, isDefault: boolean): string[] {
  const names = new Set<string>();
  if (isDefault) names.add("claude");

  const homeBase = basename(profile.claudeHome).replace(/^\./, "");
  if (homeBase === "claude") {
    names.add("claude-default");
  } else if (homeBase.startsWith("claude-")) {
    names.add(slugify(homeBase));
  }

  const label = slugify(profile.name);
  if (label && !(isDefault && label === "default-claude-code")) {
    names.add(label.startsWith("claude-") ? label : `claude-${label}`);
  }

  return [...names].filter(name => /^claude(?:-[a-z0-9][a-z0-9-]*)?$/.test(name));
}

export function plannedClaudeLaunchers(config: FrogConfig): { launchers: ClaudeLauncherEntry[]; warnings: string[] } {
  const profiles = managedClaudeProfiles(config);
  const defaultId = ensureClaudeProfiles(config).defaultProfileId ?? profiles[0]?.id;
  const seen = new Map<string, string>();
  const launchers: ClaudeLauncherEntry[] = [];
  const warnings: string[] = [];

  for (const profile of profiles) {
    for (const name of profileLauncherNames(profile, profile.id === defaultId)) {
      const existing = seen.get(name);
      if (existing && existing !== profile.id) {
        warnings.push(`launcher ${name} skipped for ${profile.name}; already assigned to ${existing}`);
        continue;
      }
      if (existing) continue;
      seen.set(name, profile.id);
      launchers.push({ name, profileId: profile.id, profileName: profile.name, claudeHome: profile.claudeHome });
    }
  }
  launchers.sort((a, b) => a.name.localeCompare(b.name));
  return { launchers, warnings };
}

function shQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
function cmdQuote(value: string): string {
  return `"${value.replace(/%/g, "%%")}"`;
}

function currentFrogpCommand(): string[] {
  const main = process.argv[1];
  if (main && existsSync(main)) return [process.execPath, realpathMaybe(main)];
  return ["frogp"];
}

function launcherExecLine(frogpCommand: string[], entry: ClaudeLauncherEntry): string {
  const command = [...frogpCommand, "claude", "run", entry.profileId, "--"].map(shQuote).join(" ");
  return `exec ${command} "$@"`;
}

function launcherScript(entry: ClaudeLauncherEntry, realClaude: string, frogpCommand: string[]): string {
  if (process.platform === "win32") {
    const command = [...frogpCommand, "claude", "run", entry.profileId, "--"].map(cmdQuote).join(" ");
    return [
      "@echo off",
      `rem ${MANAGED_MARKER}. Do not edit by hand.`,
      `set "FROGP_REAL_CLAUDE=${realClaude.replace(/%/g, "%%")}"`,
      `${command} %*`,
      "",
    ].join("\r\n");
  }
  return [
    "#!/bin/sh",
    `# ${MANAGED_MARKER}. Do not edit by hand.`,
    `FROGP_REAL_CLAUDE=${shQuote(realClaude)}`,
    "export FROGP_REAL_CLAUDE",
    launcherExecLine(frogpCommand, entry),
    "",
  ].join("\n");
}

function readManifest(): ClaudeLauncherManifest | null {
  try {
    const parsed = JSON.parse(readFileSync(manifestPath(), "utf8"));
    if (parsed?.schemaVersion === 1 && Array.isArray(parsed.launchers)) return parsed as ClaudeLauncherManifest;
  } catch { /* rebuild */ }
  return null;
}
function launcherTargetPaths(binDir: string, name: string): string[] {
  const nativeTarget = join(binDir, claudeLauncherFileName(name));
  if (process.platform !== "win32") return [nativeTarget];
  return [nativeTarget, join(binDir, name)];
}

function removeManagedLauncherFile(binDir: string, target: string): boolean {
  if (!isInside(binDir, target) || !existsSync(target)) return false;
  try {
    if (!readFileSync(target, "utf8").includes(MANAGED_MARKER)) return false;
    rmSync(target);
    return true;
  } catch {
    return false;
  }
}

export function syncClaudeLauncherShims(config: FrogConfig, options: { realClaude?: string; frogpCommand?: string[] } = {}): ClaudeLauncherSyncResult {
  const configDir = ensureConfigDirForWrite("sync Claude launcher shims");
  const binDir = join(configDir, "bin");
  mkdirSync(binDir, { recursive: true, mode: 0o700 });
  try { chmodSync(binDir, 0o700); } catch { /* best effort */ }

  const realClaude = options.realClaude ?? findRealClaudeExecutable([binDir]);
  const frogpCommand = options.frogpCommand ?? currentFrogpCommand();
  const { launchers, warnings } = plannedClaudeLaunchers(config);
  const previous = readManifest();
  const nextNames = new Set(launchers.map(entry => entry.name));
  const removed: string[] = [];

  for (const old of previous?.launchers ?? []) {
    if (nextNames.has(old.name)) {
      if (process.platform === "win32") removeManagedLauncherFile(binDir, join(binDir, old.name));
      continue;
    }
    let didRemove = false;
    for (const target of launcherTargetPaths(binDir, old.name)) {
      didRemove = removeManagedLauncherFile(binDir, target) || didRemove;
    }
    if (didRemove) removed.push(old.name);
  }

  for (const entry of launchers) {
    const target = join(binDir, claudeLauncherFileName(entry.name));
    atomicWriteFile(target, launcherScript(entry, realClaude, frogpCommand));
    if (process.platform !== "win32") chmodSync(target, 0o755);
    if (process.platform === "win32") removeManagedLauncherFile(binDir, join(binDir, entry.name));
  }

  const manifest: ClaudeLauncherManifest = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    binDir,
    realClaude,
    frogpCommand,
    launchers,
  };
  atomicWriteFile(manifestPath(), JSON.stringify(manifest, null, 2) + "\n");
  return { binDir, realClaude, frogpCommand, launchers, removed, warnings };
}

export function removeClaudeLauncherShims(): { binDir: string; removed: string[] } {
  const binDir = claudeLauncherBinDir();
  const previous = readManifest();
  const removed: string[] = [];
  for (const old of previous?.launchers ?? []) {
    let didRemove = false;
    for (const target of launcherTargetPaths(binDir, old.name)) {
      didRemove = removeManagedLauncherFile(binDir, target) || didRemove;
    }
    if (didRemove) removed.push(old.name);
  }
  const manifest = manifestPath();
  if (existsSync(manifest)) {
    try { rmSync(manifest); } catch { /* best effort */ }
  }
  return { binDir, removed };
}

function gatewayProcessActive(): boolean {
  return readPid() !== null && readActivePort() !== null;
}

type RefreshManagedCatalog = typeof import("./claude-refresh").refreshClaudeCodeModelCatalog;

/**
 * Pre-warm a managed profile's Claude Code picker cache inside that profile's own home BEFORE the
 * managed gateway Claude launches, so the picker reads a fresh catalog. Best-effort: a transient
 * refresh error never blocks the launch. The last-known-good cache policy lives entirely in the
 * refresh module; the warning here is intentionally free of tokens, paths, or other sensitive detail.
 */
async function refreshManagedProfileCatalog(
  config: FrogConfig,
  profile: ClaudeProfileRecord,
  refreshCatalog?: RefreshManagedCatalog,
): Promise<void> {
  try {
    const refresh = refreshCatalog ?? (await import("./claude-refresh")).refreshClaudeCodeModelCatalog;
    const result = await refresh(config, undefined, { claudeHome: profile.claudeHome, profileId: profile.id });
    if (result.gatewayCache.status === "failed" || result.warnings.length > 0) {
      console.warn(`frogprogsy: Claude model picker cache refresh reported a warning for profile ${profile.id}; continuing with the last known-good catalog when available.`);
    }
  } catch {
    console.warn(`frogprogsy: Claude model picker cache refresh failed for profile ${profile.id}; continuing with the last known-good catalog when available.`);
  }
}

const LAUNCHER_SPAWN_FAILURE_MESSAGE = "frogprogsy: failed to launch the Claude executable.";

/**
 * Map a spawnSync result to a launcher exit code, failing closed. A spawn that never started
 * (`result.error`, e.g. ENOENT/EACCES) or was terminated by a signal without a concrete status
 * MUST NOT surface as exit 0; a concrete numeric status (including 0) is preserved verbatim.
 * A missing executable (ENOENT) maps to the shell "command not found" code 127; any other spawn
 * error maps to 1. The failure diagnostic is fixed and redacted — it carries no path, argv, or
 * raw error body.
 */
function launcherResultExitCode(result: Pick<ReturnType<typeof spawnSync>, "status" | "signal" | "error">): number {
  if (result.error) {
    console.error(LAUNCHER_SPAWN_FAILURE_MESSAGE);
    return (result.error as NodeJS.ErrnoException).code === "ENOENT" ? 127 : 1;
  }
  if (typeof result.status === "number") return result.status;
  return 1;
}

export interface RunClaudeProfileOptions {
  realClaude?: string;
  gateway?: boolean;
  refreshCatalog?: RefreshManagedCatalog;
  spawn?: typeof spawnSync;
  exit?: (code: number) => never;
}

export async function runClaudeProfile(
  profile: ClaudeProfileRecord,
  config: FrogConfig,
  claudeArgs: string[],
  options: RunClaudeProfileOptions = {},
): Promise<never> {
  const realClaude = options.realClaude ?? findRealClaudeExecutable();
  const useGateway = options.gateway ?? gatewayProcessActive();
  const spawn = options.spawn ?? spawnSync;
  const exit = options.exit ?? ((code: number) => process.exit(code));
  let env: NodeJS.ProcessEnv;
  if (useGateway) {
    // Sync this profile's picker cache before the real Claude process starts, then launch.
    await refreshManagedProfileCatalog(config, profile, options.refreshCatalog);
    const carrier = config.gatewayAuthCarrier ?? "token-free";
    env = buildClaudeProfileRunEnv(profile, readActivePort() ?? config.port ?? DEFAULT_PORT, carrier);
  } else {
    env = buildClaudeProfileNativeEnv(profile);
  }
  const result = spawn(realClaude, claudeArgs, { stdio: "inherit", env });
  return exit(launcherResultExitCode(result));
}

export function runNativeClaude(
  claudeArgs: string[],
  options: { realClaude?: string; spawn?: typeof spawnSync; exit?: (code: number) => never } = {},
): never {
  const realClaude = options.realClaude ?? findRealClaudeExecutable();
  const spawn = options.spawn ?? spawnSync;
  const exit = options.exit ?? ((code: number) => process.exit(code));
  const result = spawn(realClaude, claudeArgs, { stdio: "inherit", env: process.env });
  return exit(launcherResultExitCode(result));
}

export function profileForLauncherName(config: FrogConfig, launcherName: string): ClaudeProfileRecord {
  if (launcherName === "claude") return resolveClaudeProfile(config, undefined);
  const { launchers } = plannedClaudeLaunchers(config);
  const matched = launchers.find(entry => entry.name === launcherName);
  return resolveClaudeProfile(config, matched?.profileId ?? launcherName.replace(/^claude-/, ""));
}

export interface RunClaudeLauncherProcessSeams {
  /** Native passthrough used when no config exists for a plain `claude` invocation. Injectable for tests. */
  runNative?: (claudeArgs: string[]) => never;
}

export async function runClaudeLauncherProcess(
  claudeArgs: string[],
  launcherName = basename(process.argv[1] ?? "claude"),
  seams: RunClaudeLauncherProcessSeams = {},
): Promise<never> {
  const runNative = seams.runNative ?? runNativeClaude;
  if (!existsSync(getConfigPath()) && launcherName === "claude") {
    return runNative(claudeArgs);
  }
  const config = loadConfig();
  const profile = profileForLauncherName(config, launcherName);
  return runClaudeProfile(profile, config, claudeArgs);
}
